// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkmSk7Nsp0_aMFBSv8wOiD2DEAhJEmdAA',
    appId: '1:57062539005:web:67a1526194c8f32cd80894',
    messagingSenderId: '57062539005',
    projectId: 'powershare-notification',
    authDomain: 'powershare-notification.firebaseapp.com',
    storageBucket: 'powershare-notification.appspot.com',
    measurementId: 'G-BRVS1Z6KMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzpdlLcffNlj9o3qU-DMp_uyH-3m-8cY',
    appId: '1:57062539005:android:bf0fe605c0f07d68d80894',
    messagingSenderId: '57062539005',
    projectId: 'powershare-notification',
    storageBucket: 'powershare-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJHHvp9unq_YofpUEWAW1N7kpcqcmb9E',
    appId: '1:57062539005:ios:1b06be9240177c01d80894',
    messagingSenderId: '57062539005',
    projectId: 'powershare-notification',
    storageBucket: 'powershare-notification.appspot.com',
    iosBundleId: 'com.example.powershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJHHvp9unq_YofpUEWAW1N7kpcqcmb9E',
    appId: '1:57062539005:ios:1b06be9240177c01d80894',
    messagingSenderId: '57062539005',
    projectId: 'powershare-notification',
    storageBucket: 'powershare-notification.appspot.com',
    iosBundleId: 'com.example.powershare',
  );
}
